---
VirtualMachine:
  #Internal IP e.g. "172.42.42.42"
  ip: "172.42.42.42"
  cpus: 2
  memory: 2048
  # Start a with a windows from the Virtualbox
  gui: false
  # Fully qualified domain name e.g. project.name.dev.domain.com
  domain: project.name.dev.domain.com
  #Apt proxy setting for a local mirror or  e.g. http://10.50.101.2:3142
  aptProxy:
  # To get a IP in local network and share it you need a bridge
  networkBridge: false
  # Puppet debug and verbose for more information
  puppetDebug: false

Mount:
  # Local folder
  from: www
